### ISSUE TITLE
document description

### ISSUE THREAD

**Issue by sunny-sjj** [muditchaudhary/RepPoints-x-Libra-R-CNN-x-Transformer-self-attention#6]
hey! I'm interested in some of the details in your code. Is there any documentation for Kqr_attention

**Comment by sunny-sjj** [comment]
it is hard to understand the Kqr_attention

**Comment by sunny-sjj** [comment]
thanks！

**Comment by muditchaudhary** [comment]
Hi,
We had written a project report on it. You can access the project report [here](https://mycuhk-my.sharepoint.com/:b:/g/personal/1155085166_link_cuhk_edu_hk/EerfCTBg_oBCpjBD3zLQgjABECTbhEqD_H83M_7iTdGFDA?e=Ok304p) 

KQR attention is explained in Section 3.2. 

Let me know if you have any other question.

**Comment by sunny-sjj** [comment]
Thanks, 
I will take a closer look at this report and consult you if I have any other questions
